version: "2"
run:
  allow-parallel-runners: true
linters:
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - cyclop
    - decorder
    - dogsled
    # - dupl
    - errcheck
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    funlen:
      lines: 80
    gosec:
      excludes:
        - G402
    revive:
      rules:
        - name: var-naming
          arguments:
            - - ID
    staticcheck:
      checks:
        - all
        - -SA5001
  exclusions:
    generated: lax
    rules:
      - path: _test\.go
        linters:
          - goconst
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

  # don't enable:
  # - depguard
  # - godox
  # - maligned,prealloc
  # - gochecknoglobals
  # - golint
  # - gochecknoinits
