run:
  allow-parallel-runners: true
linters-settings: 
    gosec: 
      excludes: 
        - G402
    staticcheck:
      checks: ["all", "-SA5001"]
    funlen:
        lines: 80
    revive:
      rules:
        - name: var-naming
          arguments: [["ID"]]
linters:
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - bidichk
    - cyclop 
    - depguard
    - decorder
    - dogsled
    # - dupl
    - errcheck
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

  # don't enable:
  # - godox
  # - maligned,prealloc
  # - gochecknoglobals
  # - golint
  # - gochecknoinits
