name: Continuous integration
on: 
 push:
   branches:
     - develop
 pull_request:
   branches:
     - '**'
jobs:
  test:
    runs-on: ubuntu-18.04
    services:
      arangodb:
        image: arangodb:3.3.23
        env:
          ARANGO_ROOT_PASSWORD: rootpass
        ports:
          - 8529/tcp
    steps:
      - name: set up golang
        uses: actions/setup-go@v1
        with:
            go-version: 1.11.13
      - name: check out code
        uses: actions/checkout@v1
      - name: unit test
        run: go test -covermode=atomic -coverprofile=profile.cov -cpu 4 -v ./...
        env:
          GOPROXY: https://proxy.golang.org
          ARANGO_USER: root
          ARANGO_PASS: rootpass
          ARANGO_HOST: localhost
          ARANGO_PORT: ${{ job.services.arangodb.ports[8529] }}
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v1.0.2
        with:
            file: ./profile.cov
            token: ${{ secrets.CODECOV_TOKEN }}
