name: Lint golang code 
on: 
  pull_request:
    branches-ignore:
      - master

jobs:
  call-lint:
    uses: dictyBase/workflows/.github/workflows/golang-lint.yaml@develop
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.event.pull_request.head.sha }}
