name: Lint golang code 
on:
  pull_request:
    types: [edited, labeled, opened, synchronize, reopened]
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: check out code
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: run linter
        uses: golangci/golangci-lint-action@v3
