name: Release 
on:
  push:
    branches:
      - master
jobs:
  semantic-release:
    runs-on: ubuntu-20.04
    steps:
      - name: set up nodejs
        uses: actions/setup-node@v1
        with:
            node-version: 12.19.0
      - name: install semantic release
        run: npm i -g semantic-release@17.x
      - name: check out code
        uses: actions/checkout@v1
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
