name: Test coverage
on:
  pull_request:
    types: [edited, labeled, opened, synchronize, reopened]
jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-20.04
    services:
      arangodb:
        image: arangodb:3.6.8
        env:
          ARANGO_ROOT_PASSWORD: rootpass
        ports:
          - 8529/tcp
    steps:
      - name: set up golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: check out code
        uses: actions/checkout@v3
      - name: unit test
        run: go test -covermode=atomic -coverprofile=profile.cov -cpu 4 -v ./...
        env:
          GOPROXY: https://proxy.golang.org
          ARANGO_USER: root
          ARANGO_PASS: rootpass
          ARANGO_HOST: localhost
          ARANGO_PORT: ${{ job.services.arangodb.ports[8529] }}
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./profile.cov
