name: Test coverage
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      arangodb:
        image: arangodb:3.6.5
        env:
          ARANGO_ROOT_PASSWORD: rootpass
        ports:
          - 8529/tcp
    steps:
      - name: set up golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.13.15
      - name: check out code
        uses: actions/checkout@v2
      - name: unit test
        run: go test -covermode=atomic -coverprofile=profile.cov -cpu 4 -v ./...
        env:
          GOPROXY: https://proxy.golang.org
          ARANGO_USER: root
          ARANGO_PASS: rootpass
          ARANGO_HOST: localhost
          ARANGO_PORT: ${{ job.services.arangodb.ports[8529] }}
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v1.0.2
        with:
          file: ./profile.cov
          token: ${{ secrets.CODECOV_TOKEN }}
  automerge:
    runs-on: ubuntu-latest
    needs: test
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: wait for code cov project to pass
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-codecov-project
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: codecov/project
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: wait for codecov patch to pass
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-codecov-patch
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: codecov/patch
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: merge
        if: steps.wait-for-codecov-project.outputs.conclusion == 'success' && steps.wait-for-codecov-patch.outputs.conclusion == 'success'
        uses: actions/github-script@v3
        with:
          script: |
            github.pulls.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              merge_method: "rebase"
            })